version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: galena
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: galena
      MYSQL_USER: galena
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
